### ISSUE TITLE
sequestering org-mode binds

### ISSUE THREAD

**Issue by ninrod** [alexmurray/evil-vimish-fold#10]
in org-mode, `za` functions as a toggle-fold command when issued on a org-subtree. 

evil-vimish-fold is sequestering those binds when I am in org-mode so `za` is not working anymore when I am in org-mode.

**Comment by alexmurray** [comment]
The point of `evil-vimish-fold` is to integrate `vimish-fold` with the usual vim / evil keybindings such as `za` etc. As such it will override any other users of the normal fold command *when it is active*.

If you want the normal `org` / `outline` commands to work in org buffers, then simply disable `evil-vimish-fold` in org buffers - then you will get the usual org bindings back.

**Comment by braham-snyder** [comment]
any chance you'd consider making `evil-vimish-fold` not global-only? I think I'd like to enable it only in `prog-mode` (and maybe `text-mode`, too?)--or do you know if there's some way to do that without removing `:global t`? thanks for the package!
