### ISSUE TITLE
Apparently can't install with latest spacemacs

### ISSUE THREAD

**Issue by vv111y** [alexmurray/evil-vimish-fold#12]
Due to dependencies I guess :      
Status: Incompatible because it depends on uninstallable packages.
    Archive: melpa
    Version: 20161103.333
  **Requires: emacs-24.4, evil-1.0.0, vimish-fold-0.2.0 (not available)**

#### System Info :computer:
- OS: darwin
**- Emacs: 25.0.50.1**
- Spacemacs: 0.200.7
- Spacemacs branch: develop (rev. 0c8af96)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
**- Evil version : 20170219.629**
- Completion: helm
- Layers: ... skipped

**Comment by alexmurray** [comment]
So it seems to say vimish-fold is not available - what package repositories do you have enabled?

**Comment by vv111y** [comment]
Apologies, did not see notification --
spacemacs uses elpa, melpa, local. 
I used a melpa recipe

**Comment by alexmurray** [comment]
Is this still an issue?

**Comment by vv111y** [comment]
I just installed it via spacemacs additional-packages, however the keybindings are not working. That's a minor issue, and different, so closing.   
Thanks
