### ISSUE TITLE
zE mapping is missing

### ISSUE THREAD

**Issue by MarcWeber** [alexmurray/evil-vimish-fold#13]
```
    diff --git a/evil-vimish-fold.el b/evil-vimish-fold.el
    index 2c98749..18ffae7 100644
    --- a/evil-vimish-fold.el
    +++ b/evil-vimish-fold.el
    @@ -44,6 +44,11 @@ See also `evil-delete-fold'."
       (when vimish-fold-mode
         (vimish-fold beg end)))
     
    +(evil-define-operator evil-vimish-fold/delete-all (beg end)
    +  "Delete all folds."
    +  (when vimish-fold-mode
    +    (vimish-fold-delete-all)))
    +
     (evil-define-operator evil-vimish-fold/create-line (beg end)
       "Create a fold from the current region.
     See also `evil-delete-fold'."
    @@ -86,6 +91,7 @@ See also `evil-create-fold'."
                 (evil-define-key 'normal map "zk" 'evil-vimish-fold/previous-fold)
                 (evil-define-key 'motion map "zk" 'evil-vimish-fold/previous-fold)
                 (evil-define-key 'motion map "zd" 'evil-vimish-fold/delete)
    +            (evil-define-key 'normal map "zE" 'evil-vimish-fold/delete-all)
                 (evil-define-key 'motion map "zf" 'evil-vimish-fold/create)
                 (evil-define-key 'motion map "zF" 'evil-vimish-fold/create-line)
                 map)
```

**Comment by alexmurray** [comment]
Thanks - did you want to send this as a PR, that way you can be listed as the author?

**Comment by alexmurray** [comment]
zE mapping doesn't work - when using this patch and typing `zE` in normal mode I see the following printed:

    z e is undefined

Seems the capital E is not getting detected - does this work for you? I am using Emacs 25.1

**Comment by alexmurray** [comment]
Have tested this again it works except after typing zE in normal mode then it seems to be waiting for more input (cursor is a half-block) and I then have to hit Enter for it to actually do the deletion...

Since it sort of works I'll merge this patch in but would be good to resolve this - @MarcWeber can you confirm it works immediately after zE for you?

**Comment by alexmurray** [comment]
The problem was your patch uses `evil-define-operator` so it wants a region - if instead this is `evil-define-command` it works as expected - added in e735d9e
