### ISSUE TITLE
add to spacemacs?

### ISSUE THREAD

**Issue by dzhwinter** [alexmurray/evil-vimish-fold#3]
i'm finding here from spacemacs discuss session. 
I'm wondering that if I want to try your package with vimish-fold?
just add to my private layer is not work at all.

**Comment by dzhwinter** [comment]
here is my config, anything is wrong?
```
(defun configlayer/init-vimish-fold ()
  (use-package vimish-fold
    :defer t
    :init
    (progn
     (setq vimish-fold-global-mode t))))

(defun configlayer/init-evil-vimish-fold ()
  (use-package evil-vimish-fold
    :defer t
    ))

```

**Comment by alexmurray** [comment]
The following works for me:

```
(use-package evil-vimish-fold
  :ensure t)

(use-package vimish-fold
  :ensure t
  :config (vimish-fold-global-mode t))
```

Try adding `:ensure t` to make sure it gets installed if is not already installed.

**Comment by pmillet** [comment]
I would love to have this in my spacemacs too but beeing quite new to spacemacs / emacs I can't figure out how install it. I tried adding your lines into the user-config part of my .spacemacs but this results in the following message:
'Error in dotspacemacs/user-config: https://melpa.org/packages/vimish-fold-20160111.102.el: Not found'

Probably this it not what I should be doing? Any help / instructions would be very welcome.

**Comment by alexmurray** [comment]
Sorry I am not familiar with spacemacs, can you try refreshing your package list? Also you'll need to add a

  (evil-vimish-fold-mode 1)

Since the initialisation process has changed since those instructions were written.

**Comment by pmillet** [comment]
Thanks for your quick response. The solution is rather trivial:
1) add the package to dotspacemacs-additional-packages 
2) add (evil-vimish-fold-mode 1) to user-config
(all in .spacemacs file)
Then, it gets installed without error message. 
( thanks to @deuill for pointing this out in the spacemacs chat )

**Comment by vv111y** [comment]
@pmillet  Did you get keybindings to work? Not showing up for me

**Comment by pmillet** [comment]
@vv111y It worked for me, but I only tested it with .cpp files.

**Comment by Kazark** [comment]
I've attempted to add it to Spacemacs: https://github.com/syl20bnr/spacemacs/pull/14047

**Comment by Kazark** [comment]
My PR has been accepted into Spacemacs. This issue can be closed.
