### ISSUE TITLE
Don't remove trailing empty lines from fold region

### ISSUE THREAD

**Issue by plm75** [alexmurray/evil-vimish-fold#7]
Hello, 
First of all, thank you and the original author of vimish-fold for this great plugin.  Without it, I'd certainly still be using vim.

I'm pretty new to spacemacs and emacs in general, so I may have missed something, but it looks like empty lines at the bottom of a folded region are trimmed:

1. create a fold (`zf`) containing multiple empty lines at the bottom
2. close the fold `zc`
3. reopen the fold `zo`: one empty line has been removed from the fold region

steps 2 and 3 can be repeated until all empty lines are gone ...

Is this by design and/or is there a way to disable that ?

**Comment by alexmurray** [comment]
Sounds like an issue in vimish-fold itself - can you please open an issue at https://github.com/mrkkrp/vimish-fold
