### ISSUE TITLE
add `zj` to go to the next fold

### ISSUE THREAD

**Issue by ninrod** [alexmurray/evil-vimish-fold#9]
[zj](http://vimdoc.sourceforge.net/htmldoc/fold.html#zj) is a quick and comfortable bind for navigating a fold packed file. 

consider including it.

**Comment by alexmurray** [comment]
Added in 37fa430 - let me know if this is suitable

**Comment by yang-ling** [comment]
@alexmurray Hi, I checked it but when I press `zj`, error happened, but no error if I press `1zj` or `2zj`. I checked the code and found that it is lack of *nil check* for `count`.

I use the following codes to overwrite the `next-fold` and `previous-fold`, and it works well for me.

```lisp
(eval-after-load 'evil-vimish-fold
  '(progn
     (evil-define-motion evil-vimish-fold/next-fold (count)
       "Go to the start of the next fold."
       :type inclusive
       (when vimish-fold-mode
         (if count
             (dotimes (_ count nil)
               (vimish-fold-next-fold))
           (vimish-fold-next-fold))))
     (evil-define-motion evil-vimish-fold/previous-fold (count)
       "Go to the start of the previous fold."
       :type inclusive
       (when vimish-fold-mode
         (if count
             (dotimes (_ count nil)
               (vimish-fold-previous-fold))
           (vimish-fold-previous-fold))))))
```

You can see I only added `(if count ...)` check.

**Comment by alexmurray** [comment]
Thanks - sorry for the bug but thanks for identifying the problem - I chose a slightly different fix - should be fixed in https://github.com/alexmurray/evil-vimish-fold/commit/674a8a894e4ae7e7f4b2608b0c9f801a548c69eb
